name: haweyati
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Location and Maps Plugins
  geocoder:
  geolocator:
  google_maps_flutter:
  flutter_google_places:
  google_maps_webservice:

  # Storage related Plugins
  hive:
  hive_flutter:
  shared_preferences:

  # l10n related Plugins (Will be removed).
  flutter_localizations:
    sdk: flutter
  easy_localization:

  # Plugins for Social Authentication
  firebase_auth:

  # Payment related Plugins
  stripe_payment:
  flutter_credit_card:

  # Network related Plugins
  dio:

  # Inter-App communication Plugins
  url_launcher:
  image_picker:
  app_settings:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  intl:
  intl_translation:
  build_runner: ^1.10.0
  hive_generator: ^0.7.0+2

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/home-page/
    - assets/images/welcome-page/
    - assets/translations/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato.ttf

    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
